---
version: "2.1"

services:
  twtxt:
    image: nicholaswilde/twtxt:latest
    container_name: twtxt-default
    environment:
      - TZ=America/Los_Angeles `# optional` \
      - PUID=1000    `# optional` \
      - PGID=1000    `# optional` \
      - OPEN_PROFILES=true
      - OPEN_REGISTRATIONS=true
      - COOKIE_SECRET=supersecretchangeme
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - data:/data
      - config:/config
volumes:
  data:
  config:
